import sublime, sublime_plugin, string

class AsciiReplacerCommand(sublime_plugin.TextCommand):

	def run(self, edit):
		for r in reversed(self.view.sel()):
			for line_r in reversed(self.view.lines(r)):
				text = self.view.substr(line_r)
				text = text.replace('& ', '&amp; ')
				text = text.replace('©', '&copy;')
				text = text.replace('™', '&trade;')
				text = text.replace('®', '&reg;')
				text = text.replace("‘", "'")
				text = text.replace("’", "'")
				text = text.replace('“', '"')
				text = text.replace('”', '"')
				text = text.replace('% ', '&#37; ')
				text = text.replace('…', '&#8230;')
				text = text.replace('--', '&mdash;')
				text = text.replace(' ', ' ')
				text = text.replace('', '')
				text = text.replace(' ', '')
				text = text.replace('$', '&#36;')
				text = text.replace('€', '&euro;')
				text = text.replace('Á', '&Aacute;')
				text = text.replace('á', '&aacute;')
				text = text.replace('É', '&Eacute;')
				text = text.replace('é', '&eacute;')
				text = text.replace('Í', '&#205;')
				text = text.replace('í', '&#237;')
				text = text.replace('Ó', '&#211;')
				text = text.replace('ó', '&#243;')
				text = text.replace('Ú', '&#218;')
				text = text.replace('ú', '&#250;')
				text = text.replace('—', '&mdash;')
				text = text.replace('à', '&agrave;')
				text = text.replace('À', '&Agrave;')
				text = text.replace('â', '&acirc;')
				text = text.replace('Â', '&Acirc;')
				text = text.replace('è', '&egrave;')
				text = text.replace('È', '&Egrave;')
				text = text.replace('ê', '&ecirc;')
				text = text.replace('Ê', '&Ecirc;')
				text = text.replace('î', '&icirc;')
				text = text.replace('Î', '&Icirc;')
				text = text.replace('ç', '&ccedil;')
				text = text.replace('Ç', '&Ccedil;')
				text = text.replace('ù', '&ugrave;')
				text = text.replace('Ù', '&Ugrave;')
				self.view.replace(edit, line_r, text)
		self.view.erase_status('ascii_replacer')
		sublime.status_message('Ascii Replacer is finished running!')
